name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

jobs:
  instalar_dependencias:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o repositório
        uses: actions/checkout@v3

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar as dependências
        run: npm install

      - name: Rodar os testes
        run: npm test

      - name: Construir a aplicação
        run: npm run build

      - name: Subir artefatos de release
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: instalar_dependencias
    environment:
      name: producao
      url: https://seu-site-deploy-url.com
    steps:
      - name: Obter o repositório
        uses: actions/checkout@v3

      - name: Realizar o deploy para o ambiente de produção
        run: |
          echo "Fazendo deploy da aplicação para o ambiente de prod"

      - name: Enviar notificação de e-mail caso falhe
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          from: ${{ secrets.EMAIL_SECRET }}
          to: ${{ secrets.EMAIL_SECRET }}
          subject: 'Falha no Pipeline de CI/CD'
          body: 'O pipeline de CI/CD deu ruim.'
          username: ${{ secrets.EMAIL_SECRET  }}
          password: ${{ secrets.EMAIL_SENHA }}
