name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

jobs:
  instalar_dependencias:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o repositório
        uses: actions/checkout@v3

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar as dependências
        run: npm install

      - name: Instalar Jest
        run: npm install -g jest

      - name: Rodar os testes
        run: npm test

      - name: Construir a aplicação
        run: npm run build

      - name: Modificar o HTML com o commit hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Commit Hash gerado: $COMMIT_HASH"  # Exibe o commit hash
          sed -i "s|<!-- COMMIT_HASH -->|$COMMIT_HASH|g" index.html  # Substitui o marcador pelo hash
          cat index.html  # Exibe o conteúdo do index.html depois da modificação

      - name: Subir artefato da release
        uses: actions/upload-artifact@v4
        with:
          name: teste-artefato
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: instalar_dependencias
    environment:
      name: teste
    steps:
      - name: Obter o repositório novamente
        uses: actions/checkout@v3

      - name: Realizar o deploy para o ambiente de teste
        run: |
          echo "Fazendo deploy da aplicação para o ambiente de teste"
