name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

jobs:
  instalar_dependencias:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o repositório
        uses: actions/checkout@v3

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar as dependencias
        run: npm install

      
      
      - name: verificar html
        run: cat index.html

      - name: Instalar Jest 
        run: npm install -g jest

      - name: Rodar os testes
        run: npm test

      - name: Construir a aplicação
        run: npm run build

      - name: Subir artefato da release
        uses: actions/upload-artifact@v4
        with:
          name: teste-artefato
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: instalar_dependencias
    environment:
      name: prod
    steps:
      - name:  repositorio
        uses: actions/checkout@v3

      - name: Realizar o deploy para o ambiente de prod 
        run: |
          echo "Fazendo deploy da aplicação para o ambiente de producao"
          run: ls 

